// Code generated by donorprofiles_gen.go from donor-profiles.csv. DO NOT EDIT.
//
// Measured: 2026-08-25
// Regenerate: go generate ./internal/server/

package server

import "time"

// donorProfilesMeasuredAt is the oldest measurement date in the table. The
// freshness guard in the tests judges the whole table by this, key exchange
// included: both githubusercontent hosts sit behind Fastly, where the
// post-quantum setting can change at any time, and a stale entry there means
// we answer with a different group than the donor we claim to be.
var donorProfilesMeasuredAt = time.Date(2026, time.August, 25, 0, 0, 0, 0, time.UTC)

// donorProfiles is the measured behaviour of each donor we may present
// ourselves as: how much ChangeCipherSpec it tolerates, and which key
// exchange it negotiates.
var donorProfiles = map[string]donorProfile{
	// alfabank.ru (confidence medium): 34/38/34 at 40ms, 35 at 10ms - one outlier at 38, floor taken
	"alfabank.ru": {CCS: ccsPolicy{Mechanism: ccsCount, Limit: 34}, KeyExchange: kxClassic},
	// api.github.com (confidence none): routes through tiredvpn0 - not measurable from this host
	"api.github.com": {CCS: ccsPolicy{Mechanism: ccsUnmeasured}, KeyExchange: kxClassic},
	// github.com (confidence none): routes through tiredvpn0 from the measuring host - probe measures our own tunnel, not the donor
	"github.com": {CCS: ccsPolicy{Mechanism: ccsUnmeasured}, KeyExchange: kxClassic},
	// gosuslugi.ru (confidence high): no count limit: 247 at 40ms (9.9s) but 400 at 10ms - time-based
	"gosuslugi.ru": {CCS: ccsPolicy{Mechanism: ccsTimeout, Timeout: 9500 * time.Millisecond}, KeyExchange: kxClassic},
	// mail.ru (confidence high): 2 on four consecutive runs, 3 at 10ms; TLS 1.2 donor, CCS is a real protocol message there not middlebox compat
	"mail.ru": {CCS: ccsPolicy{Mechanism: ccsCount, Limit: 2}, KeyExchange: kxClassic},
	// objects.githubusercontent.com (confidence none): routes through tiredvpn0 - not measurable from this host
	"objects.githubusercontent.com": {CCS: ccsPolicy{Mechanism: ccsUnmeasured}, KeyExchange: kxHybrid},
	// raw.githubusercontent.com (confidence none): routes through tiredvpn0 - not measurable from this host
	"raw.githubusercontent.com": {CCS: ccsPolicy{Mechanism: ccsUnmeasured}, KeyExchange: kxHybrid},
	// sberbank.ru (confidence high): no count limit: 240 at 40ms (9.6s) but 400 at 10ms (4.0s) - cuts on elapsed handshake time near 10s
	"sberbank.ru": {CCS: ccsPolicy{Mechanism: ccsTimeout, Timeout: 9500 * time.Millisecond}, KeyExchange: kxClassic},
	// tinkoff.ru (confidence high): 34/34/34 at 40ms and 10ms - count-based
	"tinkoff.ru": {CCS: ccsPolicy{Mechanism: ccsCount, Limit: 34}, KeyExchange: kxClassic},
	// vk.com (confidence high): 34/34/35 at 40ms, 36 at 10ms - count-based
	"vk.com": {CCS: ccsPolicy{Mechanism: ccsCount, Limit: 34}, KeyExchange: kxClassic},
	// vtb.ru (confidence high): no count limit: 248/249 at 40ms but 400 at 10ms - time-based
	"vtb.ru": {CCS: ccsPolicy{Mechanism: ccsTimeout, Timeout: 9500 * time.Millisecond}, KeyExchange: kxClassic},
	// ya.ru (confidence high): stable 33/33/33 at 40ms, 34 at 10ms - count-based
	"ya.ru": {CCS: ccsPolicy{Mechanism: ccsCount, Limit: 33}, KeyExchange: kxClassic},
	// yandex.ru (confidence high): stable 33/33/33 at 40ms and 33/34 at 10ms - count-based
	"yandex.ru": {CCS: ccsPolicy{Mechanism: ccsCount, Limit: 33}, KeyExchange: kxClassic},
}
