//go:build ignore

// Generator for donor_profiles_generated.go.
//
// The table is generated, not typed. A hand-maintained list of numbers taken
// from a measurement drifts away from the measurement silently, and the whole
// point of these values is that they match live donors. Run:
//
//	go generate ./internal/server/
//
// after replacing donor-profiles.csv with a fresh run of the probes in
// test/donor-profiles.
package main

import (
	"encoding/csv"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"
	"strings"
)

type row struct {
	sni        string
	mechanism  string
	ccsLimit   int
	timeoutMS  int
	keyEx      string
	confidence string
	measuredAt string
	note       string
}

func main() {
	in, err := os.Open("donor-profiles.csv")
	if err != nil {
		fail(err)
	}
	defer in.Close()

	records, err := csv.NewReader(in).ReadAll()
	if err != nil {
		fail(err)
	}
	if len(records) < 2 {
		fail(fmt.Errorf("donor-profiles.csv has no data rows"))
	}

	var rows []row
	measuredAt := ""
	for _, rec := range records[1:] {
		if len(rec) < 8 {
			fail(fmt.Errorf("row %q has %d fields, want 8", rec, len(rec)))
		}
		r := row{
			sni:        rec[0],
			mechanism:  rec[1],
			keyEx:      rec[4],
			confidence: rec[5],
			measuredAt: rec[6],
			note:       rec[7],
		}
		if r.ccsLimit, err = strconv.Atoi(rec[2]); err != nil {
			fail(fmt.Errorf("%s: ccs_limit: %w", r.sni, err))
		}
		if r.timeoutMS, err = strconv.Atoi(rec[3]); err != nil {
			fail(fmt.Errorf("%s: timeout_ms: %w", r.sni, err))
		}
		switch r.mechanism {
		case "count", "timeout", "unmeasured":
		default:
			fail(fmt.Errorf("%s: unknown mechanism %q", r.sni, r.mechanism))
		}
		switch r.keyEx {
		case "classic", "hybrid":
		default:
			fail(fmt.Errorf("%s: unknown key_exchange %q", r.sni, r.keyEx))
		}
		// The oldest date in the file is the one the freshness guard has to
		// judge: a table is only as current as its stalest row.
		if measuredAt == "" || r.measuredAt < measuredAt {
			measuredAt = r.measuredAt
		}
		rows = append(rows, r)
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].sni < rows[j].sni })

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by donorprofiles_gen.go from donor-profiles.csv. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// Measured: %s\n", measuredAt)
	fmt.Fprintf(&b, "// Regenerate: go generate ./internal/server/\n\n")
	fmt.Fprintf(&b, "package server\n\n")
	fmt.Fprintf(&b, "import \"time\"\n\n")
	fmt.Fprintf(&b, "// donorProfilesMeasuredAt is the oldest measurement date in the table. The\n")
	fmt.Fprintf(&b, "// freshness guard in the tests judges the whole table by this, key exchange\n")
	fmt.Fprintf(&b, "// included: both githubusercontent hosts sit behind Fastly, where the\n")
	fmt.Fprintf(&b, "// post-quantum setting can change at any time, and a stale entry there means\n")
	fmt.Fprintf(&b, "// we answer with a different group than the donor we claim to be.\n")
	fmt.Fprintf(&b, "var donorProfilesMeasuredAt = time.Date(%s, %s, %s, 0, 0, 0, 0, time.UTC)\n\n",
		measuredAt[0:4], monthExpr(measuredAt[5:7]), strings.TrimPrefix(measuredAt[8:10], "0"))

	fmt.Fprintf(&b, "// donorProfiles is the measured behaviour of each donor we may present\n")
	fmt.Fprintf(&b, "// ourselves as: how much ChangeCipherSpec it tolerates, and which key\n")
	fmt.Fprintf(&b, "// exchange it negotiates.\n")
	fmt.Fprintf(&b, "var donorProfiles = map[string]donorProfile{\n")
	for _, r := range rows {
		fmt.Fprintf(&b, "\t// %s (confidence %s): %s\n", r.sni, r.confidence, r.note)
		fmt.Fprintf(&b, "\t%q: {CCS: %s, KeyExchange: %s},\n", r.sni, ccsExpr(r), kxExpr(r.keyEx))
	}
	fmt.Fprintf(&b, "}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		fail(fmt.Errorf("formatting generated source: %w\n%s", err, b.String()))
	}
	if err := os.WriteFile("donor_profiles_generated.go", src, 0o600); err != nil {
		fail(err)
	}
}

func ccsExpr(r row) string {
	switch r.mechanism {
	case "count":
		return fmt.Sprintf("ccsPolicy{Mechanism: ccsCount, Limit: %d}", r.ccsLimit)
	case "timeout":
		return fmt.Sprintf("ccsPolicy{Mechanism: ccsTimeout, Timeout: %d * time.Millisecond}", r.timeoutMS)
	default:
		return "ccsPolicy{Mechanism: ccsUnmeasured}"
	}
}

func kxExpr(kx string) string {
	if kx == "hybrid" {
		return "kxHybrid"
	}
	return "kxClassic"
}

func monthExpr(mm string) string {
	n, err := strconv.Atoi(mm)
	if err != nil || n < 1 || n > 12 {
		fail(fmt.Errorf("bad month %q", mm))
	}
	return "time." + [...]string{
		"January", "February", "March", "April", "May", "June",
		"July", "August", "September", "October", "November", "December",
	}[n-1]
}

func fail(err error) {
	fmt.Fprintf(os.Stderr, "donorccs_gen: %v\n", err)
	os.Exit(1)
}
