{{- if and .Values.client.enabled (not .Values.client.tomlConfig) (not .Values.client.server.existingSecret) -}}
{{- include "tiredvpn.validate" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tiredvpn.client.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tiredvpn.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
type: Opaque
data:
  {{ include "tiredvpn.client.secretAddressKey" . }}: {{ required "client.server.address is required" .Values.client.server.address | b64enc | quote }}
  {{ include "tiredvpn.client.secretSecretKey" . }}: {{ required "client.server.secret is required" .Values.client.server.secret | b64enc | quote }}
{{- end }}
