{{- if and (include "tiredvpn.client.socks.enabled" .) .Values.client.config.api.enabled .Values.client.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tiredvpn.client.socks.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.client.metrics.serviceMonitor.namespace }}
  labels:
    {{- include "tiredvpn.client.socks.labels" . | nindent 4 }}
    {{- with .Values.client.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "tiredvpn.client.socks.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: api
      path: /metrics
      interval: {{ .Values.client.metrics.serviceMonitor.interval }}
      {{- with .Values.client.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      honorLabels: {{ .Values.client.metrics.serviceMonitor.honorLabels }}
      {{- with .Values.client.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.client.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
