{{- if and .Values.server.enabled (not .Values.server.tomlConfig) .Values.server.config.upstream.addr (not .Values.server.config.upstream.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tiredvpn.server.upstreamSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tiredvpn.server.labels" . | nindent 4 }}
type: Opaque
data:
  upstream-secret: {{ required "server.config.upstream.secret is required when upstream.addr is set and no existingSecret" .Values.server.config.upstream.secret | b64enc | quote }}
{{- end }}
