{{- if and .Values.server.enabled .Values.server.tls.create -}}
{{- include "tiredvpn.validate" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tiredvpn.server.tlsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tiredvpn.server.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.server.tls.cert | b64enc | quote }}
  tls.key: {{ .Values.server.tls.key | b64enc | quote }}
{{- end }}
